# Generated by Django 5.0.1 on 2024-03-01 17:55

import cpf_field.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', cpf_field.models.CPFField(error_messages={'unique': 'Já existe um usuário com este CPF. Por favor, escolha outro.'}, max_length=14, null=True, unique=True, verbose_name='cpf')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um usuário com este e-mail. Por favor, escolha outro.'}, max_length=50, null=True, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('instituicao', models.CharField(max_length=50, null=True)),
                ('vinculo', models.CharField(choices=[('contratado', 'Contratado'), ('efetivo', 'Efetivo'), ('comissionado', 'Comissionado'), ('outro', 'Outro')], max_length=30, null=True)),
                ('cargo', models.CharField(max_length=30, null=True)),
                ('ch', models.PositiveIntegerField(default=20, null=True)),
                ('rg', models.CharField(max_length=100, null=True)),
                ('org_expedidor', models.CharField(max_length=20, null=True)),
                ('endereco', models.CharField(max_length=100, null=True)),
                ('escolaridade', models.CharField(max_length=50, null=True)),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='imagens_perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUsuario',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servidores_app.usuario')),
            ],
            bases=('servidores_app.usuario',),
        ),
    ]
