# Generated by Django 5.0.1 on 2024-03-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='org_expedidor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
