# Generated by Django 5.0.1 on 2024-03-19 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'O INEP deve ter exatamente 8 dígitos.')])),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
