# Generated by Django 5.0.1 on 2024-04-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas_conectadas_app', '0003_escolas_latitude_escolas_longetude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escolas',
            old_name='longetude',
            new_name='longitude',
        ),
    ]
