# Generated by Django 5.0.1 on 2024-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas_conectadas_app', '0004_rename_longetude_escolas_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolas',
            name='endereco',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
