# Generated by Django 5.0.1 on 2024-04-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('estoque', 'Estoque'), ('manutencao', 'Manutenção'), ('com_servidor', 'Com servidor'), ('inativo', 'Inativo')], max_length=255)),
                ('tipo', models.CharField(blank=True, choices=[('chromebook', 'Chromebook'), ('notebook', 'Notebook')], max_length=255)),
                ('nome_servidor', models.CharField(blank=True, max_length=100)),
                ('numero_de_serie', models.CharField(blank=True, max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documents/')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='dispositivos_app.dispositivo')),
            ],
        ),
    ]
